### ISSUE TITLE
A lot of events to InitialState

### ISSUE THREAD

**Issue by wmoindrot** [initialstate/wunderground-sensehat#11]
Really enjoyed following this github, well written, kept up-to-date, easy to follow, good outcome, with enough challenges contained within it. I followed it as a replacement to an older approach of using a Google Doc to log data from SenseHat.

However it ripped through my 25k free monthly events. I don't believe InitialState offer the free pricing tier anymore, so anyone else following it would have to experiement within the 14-day free trial of the Individual trial. I can understand the rationale given in the intro to the wiki about exploring your home data overlayed onto global weather, but in posing data from Darksky onto InitialState, with three sensors from the SenseHat that's 40 events per cycle. The novice (me) not realising the true nature of an event, will exacerbate things by then decreasing the time between streams to IS, for me that was once every 30 seconds in order to see fast changes in environment. Forgetting to set this back to a higher number meant that at 4800 events per hour, I'd run out of my free events in the night. And we're still quite early in the month for a refresh of events, so that's put things on hold somewhat. I have raised a ticket with IS Support in the hope that there might be some flexibility. I really like the platform having used it only a couple of times, and I want to support the company and keep things going, but the pricing of the bottom Individual tier is too steep for me at the moment with this being just a short-term hobby project.

I think it would be good to update the wiki with a warning about this, and noticing that some of people following aren't that interested in the Darksky data, tell them how to comment out those lines in the code that print out to IS.

Thanks, Will

**Comment by jrbail01** [comment]
Hey Will. We are days away from releasing a new data streaming service with completely different pricing. I think it will address your concerns. Hold tight for a few more days ...

**Comment by wmoindrot** [comment]
Thanks @jrbail01, one of your colleagues got back to me on the support and let me know about this, and it seems like something which will fill the gap for the hobbyist. Regards, Will
