### ISSUE TITLE
Disconnection issue

### ISSUE THREAD

**Issue by chintito4ever** [initialstate/wunderground-sensehat#14]
I followed everything in this article mentioned , everything works fine except I close ssh terminal after running “python darksky.py” command. It streams data to initial state as long as I keep open ssh terminal. I have tried to keep it open for hours but stops working after. What am I doing wrong?

**Comment by jrbail01** [comment]
You need to use nohup (which stands for no hang up) to keep the process running even if the parent terminal session ends. 

Use the following command:
nohup python darksky.py &

The & sends the process to the background so you can keep using the same terminal session after executing the command.

**Comment by chintito4ever** [comment]
It worked. Thank you so much.

**Comment by chintito4ever** [comment]
Hi, looks like nohup doesn't work anymore! what should I do? TY
