### ISSUE TITLE
Unavailability to request api key from Wounderground 

### ISSUE THREAD

**Issue by imjoaki** [initialstate/wunderground-sensehat#16]
Anyone knows if the posibility to get api keys for Wounderground is still there? I'm trying to put a personal weather project together and I cannot get the key because _"You must own a Personal Weather Station in order to generate an API key."_ 

Any suggestions or confirmations on this one?

**Comment by jrbail01** [comment]
Yeah, both Wunderground and DarkSky cut off free API keys. You can use Weatherstack (which is also built into Initial State as a data integration now).
