### ISSUE TITLE
ISStreamer failed to create or find bucket after a number of attempts

### ISSUE THREAD

**Issue by perrycannon** [InitialState/wunderground-sensehat#2]
My sense hat_wunderground.py was working, now there is an error "ISStreamer failed to create or find bucket after a number of attempts"

I don't know why this error has occurred. Is this an issue with wunderground?

Thank you

**Comment by jrbail01** [comment]
You reached your stream limit in January (25K events) and, for some reason, it didn’t get reset for February.  This is fixed now.  Let me know if you have anymore issues.  

Jamie Bailey 
Founder/CEO
Initial State 




tel 859-475-3291

**Comment by stefsaladino** [comment]
same for me today.... 
thanks!
Stefania

**Comment by aesco57** [comment]
My sense hat_wunderground.py was working, now there is an error "ISStreamer failed to create or find bucket after a number of attempts"
Is this an issue with wunderground?  Any help would be appreciated.  Thanks

**Comment by jrbail01** [comment]
This message is typically associated with a connection issue with your device. Make sure you have a solid internet connection.

**Comment by aesco57** [comment]
Okay.  Thanks for quick response.
