### ISSUE TITLE
Helpppppppp

### ISSUE THREAD

**Issue by CousinEd** [initialstate/wunderground-sensehat#4]
Hello, Great project. I have it up and running but now I have 2 last questions. 1. How can I get the hat's leds to work with this project? 2. How can I set up and Call to run my last sudo python "

sudo python sensehat_wunderground.py" command that will sit on my desktop?  (aka I just want to push a button and it opens up and runs by itself)

Thanks Ed

**Comment by jrbail01** [comment]
You can use the LEDs on the sensehat by using the methods built into the SenseHat library. For example, you could display a scrolling message in the def main(): function using a single line of Python such as:

sense.show_message("Hello World")

Check out https://www.raspberrypi.org/learning/getting-started-with-the-sense-hat/worksheet/ for more information and options.

To create a shortcut on your desktop to run the script do the following:
$ cd ~/Desktop
$ touch run_weather
$ chmod u+x run_weather
$ nano run_weather
Inside of nano, create a bash script. Something like:
#!/bin/bash
sudo python /home/pi/sensehat_wunderground/sensehat_wunderground.py 
<save and exit>
