### ISSUE TITLE
rawtides with Geocoding outside the USA

### ISSUE THREAD

**Issue by guifeliper** [initialstate/wunderground-sensehat#6]
Hello, 
I'm trying to use the rawTides information outside the USA. 
The common link is http://api.wunderground.com/api/key/rawtide/q/CA/San_Francisco.json
For inside the USA, but I want that for outside the USA. Using, for example, an GeoCoding. 
But seems not to be accessible, do you know anything about that?

http://api.wunderground.com/api/key/geolookup/q/41.1579440,-8.6291050.json

**Comment by jrbail01** [comment]
I am not sure how to use GeoCoding other than to get the nearest weather station. To use rawTides outside of US, you would do something like this: http://api.wunderground.com/api/5ce3e025f0d79cde/rawtide/q/France/Nice.json .

**Comment by jrbail01** [comment]
Wunderground no longer gives out free API keys. This tutorial has migrated to use the Dark Sky API.
