### ISSUE TITLE
Weather Underground API - no longer gives out free keys

### ISSUE THREAD

**Issue by mmgarland3** [initialstate/wunderground-sensehat#7]
You may wish to update this content - IBM has discontinued issuing free API keys for the Weather Underground API as of around May 15, 2018, and may discontinue the free API service at any time.

https://apicommunity.wunderground.com/weatherapi/topics/weather-underground-api-changes

**Comment by jrbail01** [comment]
Thanks for the heads up. That sucks. Looks like this tutorial needs to migrate to https://www.aerisweather.com/.

**Comment by stellarore** [comment]
Aeris only provides the free dev account for 2 months.  

There's also DarkSky, OpenWeatherMap, NOAA NWS, Yahoo, WorldWeatherOnline

**Comment by jrbail01** [comment]
This tutorial has been updated to use the Dark Sky API.
