### ISSUE TITLE
initialstate no longer offering triggers or embed URLs to free accounts

### ISSUE THREAD

**Issue by jimmyeao** [initialstate/wunderground-sensehat#9]
As in the subject, it seems initialstate no longer offering triggers or embed URLs to free accounts, which is a shame as it would be nice to embed the dashboard on my site.

**Comment by davidsulpy** [comment]
Hi @jimmyeao Initial State has never actually offered triggers or embed URLs to free accounts. These features have always exclusively been for our paid accounts since they actually cost Initial State money to provide.
